[package]
name = "example_tuidocs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
faker_rand = "0.1.1"
lipsum = "0.9.0"
rand = "0.8.5"
tuidocs = { version = "0.1.0", path = "../../tuidocs" }
