[package]
name = "test_tuidocs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lipsum = "0.9.0"
tuidocs = { version = "0.1.0", path = "../../tuidocs" }
